config/routes.rb
Hrmage::Application.routes.draw do

  devise_for :accounts, :controllers => { :registrations => "registrations" }
  resources :accounts, :only => [:show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  get 'my_leaves' => "home#my_leaves"
  get 'my_claims' => "home#my_claims"
  get 'my_salary' => "home#my_salary"
  get 'my_salary_show/:payslip_id' => "home#my_salary_show"
  get 'sign_in' => "home#sign_in"
  get 'sign_up' => "home#sign_up"
  get 'calendar' => "home#calendar"
  get 'print_salary' => "home#print_salary"
  get 'approvals' => "home#approvals"
  resources :organizations do
    resources :attendances
    resources :claim_subjects
    resources :activities
    resources :payslip_settings
    resources :claims
    resources :positions do
      resources :position_settings
    end
    resources :account_organizations do
      resources :access_levels
    end
    resources :departments
    resources :leaves
    resources :leave_types
    resources :organization_settings do
      resources :organization_holidays do
        post 'get_and_update_holiday' => "organization_holidays#get_and_update_holiday"
      end
    end
    resources :employees do
      resources :payslips
      resources :employee_variables
      resources :employee_departments
      resources :documents
      get 'edit_login_info' => 'employees#edit_login_info'
      patch 'edit_login_info' => 'employees#update_login_info'
      get 'new_login' => 'employees#new_login'
      post 'new_login' => 'employees#create_login'
    end
    post 'end_of_year_action' => 'organizations#end_of_year_action'
  end
  resources :after_signup
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !account_signed_in?
      if current_organization.id.nil?
        render layout: "marketing"
      else
        redirect_to new_account_session_path
      end
    end

    if account_signed_in?
      if !current_employee.nil?
        if !current_employee.position.nil?
          @my_leaves = current_employee.leaves.order(id: :desc)
          authenticate_account!
          @my_claims = current_employee.claims.order(id: :desc)
          @claims_remaining_percentage = (current_employee.claims.where(status: "Approved", date: DateTime.now.beginning_of_month..DateTime.now.end_of_month).sum :amount_cents)/current_employee.position.monthly_max_claims_cents
        end
      end
    end
  end
  
  def my_leaves
    authenticate_account!
    @my_leaves = current_employee.leaves.order(start_date: :desc).page(params[:page]).per(5) if !current_employee.nil?
  end
  
  def my_claims
    authenticate_account!
    @my_claims = current_employee.claims.order(id: :desc).page(params[:page]).per(5) if !current_employee.nil?
    @claims_remaining_percentage = (current_employee.claims.where(status: "Approved", date: DateTime.now.beginning_of_month..DateTime.now.end_of_month).sum :amount_cents)/current_employee.position.monthly_max_claims_cents
  end

  def my_salary
    authenticate_account!
    @my_salarys = current_employee.payslips.order(date: :asc) if !current_employee.nil?
  end

  def my_salary_show
    @payslip = Payslip.find(params[:payslip_id])
    @base_salary_cents = @payslip.base_salary_cents
    @total = 0
    
    if @payslip.include_affected_leave
      @affected_leave = []
      current_employee.leaves.where(status: "Approved", start_date: @payslip.leave_start_date..@payslip.leave_end_date).each do |leave|
        if leave.leave_type.affected_entity.include?("salary")
          @affected_leave << leave
        end
      end
      affected_leave_total = 0
      @affected_leave.each do |leave|
        affected_leave_calculation = 0
        affected_leave_calculation = salary_calculate(leave.leave_type, @base_salary_cents,leave.duration_seconds)
        affected_leave_total = affected_leave_total + affected_leave_calculation
      end
      @base_salary_cents = @base_salary_cents + affected_leave_total
    end
    
    
    if @payslip.include_claim
      @claims = current_employee.claims.where(status: "Approved", created_at: @payslip.claim_start_date..@payslip.claim_end_date)
    end
    
    if @payslip.employee_id != current_employee.id
      redirect_to(root_path, alert: "You are not authorize to view this.")
    end
  
  end

  def print_salary
    @payslip = Payslip.find(params[:payslip_id])
    @base_salary_cents = @payslip.base_salary_cents
    @total = 0
    
    if @payslip.include_affected_leave
      @affected_leave = []
      current_employee.leaves.where(status: "Approved", start_date: @payslip.leave_start_date..@payslip.leave_end_date).each do |leave|
        if leave.leave_type.affected_entity.include?("salary")
          @affected_leave << leave
        end
      end
      affected_leave_total = 0
      @affected_leave.each do |leave|
        affected_leave_calculation = 0
        affected_leave_calculation = salary_calculate(leave.leave_type, @base_salary_cents,leave.duration_seconds)
        affected_leave_total = affected_leave_total + affected_leave_calculation
      end
      @base_salary_cents = @base_salary_cents + affected_leave_total
    end
    
    
    if @payslip.include_claim
      @claims = current_employee.claims.where(status: "Approved", created_at: @payslip.claim_start_date..@payslip.claim_end_date)
    end
    
    if @payslip.employee_id != current_employee.id
      redirect_to(root_path, alert: "You are not authorize to view this.") and return
    end
    render layout: "blank"
  end
  
  def sign_in
    if !account_signed_in?
      render layout: "marketing"
    else
      redirect_to root_path, notice: "You are already signed in."
    end
  end

  def sign_up
    if !account_signed_in?
      render layout: "marketing"
    else
      redirect_to root_path, notice: "You are already signed in."
    end
  end

  def calendar
    
    @my_leaves = current_employee.leaves
    @leave_types = current_organization.leave_types
    
    @working_hours = (current_organization.organization_setting.nil? ? 8.0 : current_organization.organization_setting.average_working_hour)
    @month = !params[:date].blank? ? params[:date][:month].to_i : DateTime.now.month
    @year = !params[:date].blank? ? params[:date][:year].to_i : DateTime.now.year
    @date = DateTime.new(@year, @month)
    @month_collection = [
    ["January", 1], 
    ["February", 2], 
    ["March", 3], 
    ["April", 4], 
    ["May", 5], 
    ["June", 6], 
    ["July", 7], 
    ["August", 8], 
    ["September", 9], 
    ["October", 10], 
    ["November", 11], 
    ["December", 12]]
    
    @employees = []

    current_employee.departments.each do |department| 
      department.employees.each do |employee|
        @employees << employee
      end
    end
    @employees = @employees.uniq

    if !current_organization.organization_setting.nil?
      @workday = [false,false,false,false,false,false,false,false]
      @workday[1] = true if !current_organization.organization_setting.monday.blank? && current_organization.organization_setting.monday != 0
      @workday[2] = true if !current_organization.organization_setting.tuesday.blank? && current_organization.organization_setting.tuesday != 0
      @workday[3] = true if !current_organization.organization_setting.wednesday.blank? && current_organization.organization_setting.wednesday != 0
      @workday[4] = true if !current_organization.organization_setting.thursday.blank? && current_organization.organization_setting.thursday != 0
      @workday[5] = true if !current_organization.organization_setting.friday.blank? && current_organization.organization_setting.friday != 0
      @workday[6] = true if !current_organization.organization_setting.saturday.blank? && current_organization.organization_setting.saturday != 0
      @workday[7] = true if !current_organization.organization_setting.sunday.blank? && current_organization.organization_setting.sunday != 0
    end
    
  end

  def approvals
    @my_leaves = current_employee.leaves.where(status: "Approved").order(start_date: :desc).page(params[:page]).per(5) if !current_employee.nil?
  end

end

app/views/home/_not_sign_in.html.erb
<div id="superContainer">
  <div class="section">
    <ul id="scene" class="scene">
      <li class="layer" data-depth="0.2"><div class="background"></div></li>

      <li class="layer" data-depth="0">
        <div class="row first-page hide-for-medium hide-for-small">
          <div class="large-12 columns ">
            <div class="row">
              <div class="large-5 columns">
                <center>
                  <h1>Let's get started.</h1>
                  <p>OfficeMage magic for your office.</p>
                </center>
                <%= link_to "Register Now", new_account_registration_path, class: "button radius" %>
              </div>
            </div>
          </div>
        </div>
        <div class="row first-page hide-for-large">
          <div class="large-12 columns">
            <center>
              <h1><strong>Let's get started.</strong></h1>
              <p>OfficeMage magic for your office.</p>
            </center>
            <%= link_to "Register Now", new_account_registration_path, class: "button radius" %>
          </div>
        </div>
      </li>
    </ul>
  </div>

  <div class="section second-page">
    <div class="row" data-equalizer>
      <div class="large-6 small-6 columns">
        <fieldset class="box-line" data-equalizer-watch>
          <legend><%= image_tag("icon/Flaticon_11296.png", class: "icon-image-size th")%></legend>
          <h5><strong>An office made for you</strong></h5>
          <h6>Officemage.com is a new Human Resource System that just made for your company. </h6>
        </fieldset>
      </div>
      <div class="large-6 small-6 columns">
        <fieldset class="box-line" data-equalizer-watch>
          <legend><%= image_tag("icon/Flaticon_181.png", class: "icon-image-size th")%></legend>
          <h5><strong>Access anywhere in world</strong></h5>
          <h6>
            Many desktop publishing packages and web page editors now use Lorem Ipsum
          </h6>
        </fieldset>
      </div>
    </div>
    <div class="row" data-equalizer>
      <div class="large-6 small-6 columns">
        <fieldset class="box-line" data-equalizer-watch>
          <legend><%= image_tag("icon/Flaticon_24587.png", class: "icon-image-size th")%></legend>
          <h5><strong>Like a magic</strong></h5>
          <h6>
            Many desktop publishing packages and web page editors now use Lorem Ipsum
          </h6>
        </fieldset>
      </div>
      <div class="large-6 small-6 columns">
        <fieldset class="box-line" data-equalizer-watch>
          <legend><%= image_tag("icon/Flaticon_1712.png", class: "icon-image-size th")%></legend>
          <h5><strong>Easy setting</strong></h5>
          <h6>
            Customize your own setting with OfficeMage. It is easy as 1, 2 ,3!
          </h6>
        </fieldset>
      </div>
    </div>
  </div>

  <div class="section section-three">
    <div class="row">
      <div class="large-4 columns"></div>
      <div class="large-8 columns">
        <div class="text">
          <h1>Haven't subscribe yet? </h1><h1> Subscribe now and enjoy.</h1>
          <a href="#" class="button radius">Subscribe</a>
        </div>
      </div>
    </div>
  </div>

  <div class="section">
    <ul class="scene">
      <li>
        <div class="row">
          <div class="large-6 columns">
            <p>
              <h1 class="text-justify">AlphaMelon Sdn Bhd</h1>
            </p>
            <p>
              <h4 class="text-justify">
                We always look forward to meet new awesome people and discuss brilliant project ideas. Come visit us! We have a great place to sit.
              </h4>
            </p>
            <p class="text-justify">
              <h2 class="subheader text-justify">Our contact details</h2>
              <h4 class="text-justify">
                <strong>AlphaMelon Sdn Bhd</strong><br>
                11, 13 & 15, Jalan Juruanalisis U1/35<br>
                Hicom Glenmarie Industrial Park<br>
                40150 Shah Alam<br>
                Selangor Darul Ehsan Malaysia<br>
                Tel: +6012-3930211
              </h4>
            </p>
          </div>
          <div class="large-6 columns">
          </div>
        </div>
        <div class="row">
          <div class="large-12 columns">
            <center>
            <h6>Office Mage - © 2013 Alpha Melon Sdn Bhd</h6>
            </center>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/home/_select_domain.html.erb
<div class="row">
  <div class="large-8 large-centered columns">
    <div class="panel large-12">
      <%= t :sign_in_go_domain %>
      <%= link_to t(:logout), destroy_account_session_path, class: "right", method: :delete %>
    </div>
    <ul>
      <% current_account.organizations.each do |org| %>
        <li><%= link_to org.name.capitalize, host: org.domain %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/_select_year_month.html.erb
<div class="row">
  <div class="large-8 columns">
  <h3><%= t :leave_calendar %></h3>
    <%= simple_form_for :date, wrapper: :custom, url: calendar_path(current_organization), method: :get do |f| %>
      <%= f.input :year, collection: (@year-3..@year+3), include_blank: false, selected: @year %>
      <%= f.input :month, collection: @month_collection, include_blank: false, selected: @month %>
        
      <div class="row">
        <div class="large-3 small-3 columns"></div>
        <div class="large-9 small-9 columns">
          <%= f.submit t(:change_date), class: "button success"%>
        </div>
      </div>
    <% end %> 
  </div>
</div>

app/views/home/_sign_in.html.erb
<% if !current_organization.new_record?%>
  <% if !current_employee.nil?%>
    <% if !current_employee.position.nil?%>
      <div class="content-header">
        <div class="row">
          <div class="large-9 large-centered columns">
            <h3>Welcome, you are now in <%= current_organization.name.capitalize if !current_organization.new_record?%> Organization</h3>
          </div>
        </div>
      </div>
      <div class="dashboard row" data-equalizer>
        <div class="large-4 small-12 columns" >
          <h3><%= t :leaves %></h3>
          <div class="large-12 panel columns" data-equalizer-watch>
            <% current_organization.leave_types.order(id: :asc).each do |leave_type|%>
              <div class="large-12 small-12 columns">
                <h6><%= t :available %> <%= leave_type.name %></h6>
              </div>
              <div class="large-12 columns">
                <div class="large-2 small-2 columns">
                  <h6 class="text-left">
                    <%= EmployeeVariable.where(employee_id: current_employee.id, leave_type_id: leave_type.id).first_or_create.available_leaves_seconds/working_hours/60/60 %>/<%= !current_employee.position.position_settings.where(leave_type_id: leave_type.id).blank? ? 
                    current_employee.position.position_settings.where(leave_type_id: leave_type.id).first.max_leaves_seconds/working_hours/60/60 : leave_type.default_count_seconds/working_hours/60/60%>
                  </h6>
                </div>
                <div class="progress success large-8 small-8 columns">
                  <span class="meter" style="width: 
                  <%= EmployeeVariable.where(employee_id: current_employee.id, leave_type_id: leave_type.id).first_or_create.available_leaves_seconds*100/
                  (!current_employee.position.position_settings.where(leave_type_id: leave_type.id).blank? ? 
                    current_employee.position.position_settings.where(leave_type_id: leave_type.id).first.max_leaves_seconds : leave_type.default_count_seconds) %>%; background: <%= leave_type.colour%>"></span>
                </div>
              </div>
              <hr>
            <% end %>
            <h6 class="clearfix"><%= link_to t(:view_more),  my_leaves_path, id: "my_leaves", class: "right" %></h6>
          </div>
        </div>
        <div class="large-4 small-12 columns" >
          <h3><%= t :claims %></h3>
          <div class="large-12 panel columns" data-equalizer-watch>
            <h6><strong><%= t :claims_for %> <%=Date::MONTHNAMES[Date.today.month]%></strong></h6>
            <div class="large-12 columns">
              <div class="large-12 small-12 columns">
                <h6 class="text-left">
                <%= t :claim_amout %>
                <%= humanized_money_with_symbol (current_employee.claims.where(status: "Approved", date: DateTime.now.beginning_of_month..DateTime.now.end_of_month).sum :amount_cents).to_f/100 %></h6>
                <h6>
                <%= t :claim_remaining %> <%= humanized_money_with_symbol (current_employee.position.monthly_max_claims_cents - (current_employee.claims.where(status: "Approved", date: DateTime.now.beginning_of_month..DateTime.now.end_of_month).sum :amount_cents)).to_f/100 %>
                </h6>
              </div>
            </div>
            <h6 class="clearfix"><%= link_to t(:view_more),  my_claims_path, id: "my_claims", class: "right" %></h6>
          </div>
        </div>
        <div class="large-4 small-12 columns" >
          <h3><%= t :salary %></h3>
          <div class="large-12 panel columns" data-equalizer-watch>
            <table class="large-12">
              <thead>
                <th><%= t :working_date %></th>
                <th><%= t :base_salary %></th>
                <th><%= t :commission %></th>
              </thead>
              <tbody>
                <% current_employee.payslips.order(id: :asc).each do |payslip| %>
                  <tr>
                    <td><%= payslip.date.to_date %></td>
                    <td><%= humanized_money_with_symbol payslip.base_salary %></td>
                    <td><%= humanized_money_with_symbol payslip.commission %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <h6 class="clearfix">
              <%= link_to t(:view_more), my_salary_path, id: "my_salary", class: "right" %>
            </h6>
          </div>
        </div>
      </div>
    <% else %>
      <p><%= t :sign_in_no_position_yet %></p>
    <% end %>
  <% else %>
    <p><%= t :sign_in_no_profile_yet %></p>
  <% end %>
<% end %>

<% if current_organization.id.nil? %>
  <%= render "select_domain" %>
<% end %>

app/views/home/approvals.html.erb
<div class="content-header">
  <div class="row">
    <div class="large-9 large-centered columns">
      <h2><%= t :approvals %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <table class="large-12">
      <thead>
        <th><%= t :type %></th>
        <th><%= t :reason %></th>
        <th><%= t :duration%></th>
        <th><%= t :when %></th>
        <th><%= t :status %></th>
      </thead>
      <tbody>
      <% @my_leaves.each do |leave| %>
        <tr>
          <td><%= leave.leave_type.name %></td>
          <td><%= leave.comment %></td>
          <td><%= (leave.duration_seconds)/60/60/24 %> <%= t :b_days %></td>
          <td><%= leave.start_date.to_date.strftime("%d/%m/%Y") %> - <%= (leave.start_date.to_date + ((leave.duration_seconds)/60/60/24-1).days).strftime("%d/%m/%Y") %></td>
          <td><%= leave.status %></td>
        </tr>
      <%end%>
      </tbody>
    </table>
    <%= paginate @my_leaves %>
  </div>
</div>

app/views/home/calendar.html.erb
<%= render "select_year_month" %>

<% if current_organization.organization_setting.nil? %>
  <%= render "leaves/without_setting"%>
<% else %>
  <%= render "leaves/with_setting" %>
<% end %>

app/views/home/coming_soon.html.erb
<div class="row coming-header">
  <div class="large-8 large-centered columns">

    <div class="large-6 large-centered columns">
      <center>
        <%= image_tag('logo/hrmerge-logo.jpg') %>
      </center>
    </div>

    <div class="large-12 large-centered columns">
      <center>
        <h1>UNDER <strong><span class="coming-color">CONSTRUCTION</span></strong></h1>
        <h4 class="coming-color">"MAGIC FOR YOUR OFFICE, COMING SOON. . ."</h4>
        <h6>By AlphaMelon Sdn Bhd</h6>
      </center>
    </div>

  </div>
</div>

app/views/home/index.html.erb
<% if account_signed_in? %>
  <%= render "sign_in" %>
<% else %>
  <%= render "not_sign_in" %>
<% end %>

app/views/home/my_claims.html.erb
<div class="row">
  <div class="large-12 small-12 columns">
    <h1><%= t :my_claims %></h1>
    <hr>
  </div>

  <div class="large-12 small-12 columns">
    <h5><strong><%= t :claims_for %> <%=Date::MONTHNAMES[Date.today.month]%></strong></h5>
  </div>
  <div class="large-12 columns">
    <h6 class="text-left">
      <%= t :claim_amout %>:
      <%= humanized_money_with_symbol (current_employee.claims.where(status: "Approved", date: DateTime.now.beginning_of_month..DateTime.now.end_of_month).sum :amount_cents).to_f/100 %></h6>
    <h6>
      <%= t :claim_remaining %>: <%= humanized_money_with_symbol (current_employee.position.monthly_max_claims_cents - (current_employee.claims.where(status: "Approved", date: DateTime.now.beginning_of_month..DateTime.now.end_of_month).sum :amount_cents)).to_f/100 %>
    </h6>
  <hr>
  </div>
  <div class="large-12 columns">
    <h2><%= t :history %></h2>
    <table class="large-12">
      <thead>
        <th><%= t :subject %></th>
        <th><%= t :working_date %></th>
        <th><%= t :amount %></th>
        <th><%= t :comment %></th>
        <th><%= t :status %></th>
        <th><%= t :action_by %></th>
      </thead>
      <tbody>
      <% @my_claims.each do |claim| %>
        <tr>
          <td><%= claim.subject %></td>
          <td><%= claim.date.to_date.strftime("%d/%m/%Y") %></td>
          <td><%= humanized_money_with_symbol claim.amount %></td>
          <td><%= claim.comment %></td>
          <td><%= claim.status %></td>
          <td><%= claim.action_by.nil? ? t(:no_action_yet) : claim.action_by.profiles.where(organization_id: current_organization.id).first.last_name %></td>
        </tr>
      <%end%>
      </tbody>
    </table>
    <%= paginate @my_claims %>
  </div>
</div>

app/views/home/my_salary.html.erb
<div class="row">
  <div class="large-12 small-12 columns">
    <h1><%= t :my_salary %></h1>
    <hr>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <table class="large-12">
      <thead>
        <th><%= t :working_date %></th>
        <th><%= t :base_amount %></th>
        <th><%= t :commission %></th>
        <th><%= t :note %></th>
        <th><%= t :action %></th>
      </thead>
      <tbody>
        <% @my_salarys.each do |salary| %>
        <tr>
          <td><%= salary.date.to_date %></td>
          <td><%= humanized_money_with_symbol salary.base_salary %></td>
          <td><%= humanized_money_with_symbol salary.commission %></td>
          <td><%= salary.note %></td>
          <td><%= link_to t(:show), "my_salary_show/#{salary.id}", 
          class: "fi-eye", id: "show_my_salary"%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/my_salary_show.html.erb
<div class="row">
  <div class="large-9 large-centered columns">
    <h2><%= current_employee.full_name.capitalize %> (<%= @payslip.date.to_date %>) </h2>
  </div>
</div>

<div class="row">
  <div class="large-9 large-centered columns">
    <table class="large-12">
      <thead>
        <tr>
          <th colspan="2"><center><%= t :payments %></center></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= t :working_date %></td>
          <td><%= @payslip.date.to_date %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th><%= t :description %></th>
          <th><%= t :amount %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= t :base_salary %></td>
          <td><%= humanized_money_with_symbol @payslip.base_salary %></td>
        </tr>
        <tr>
          <td><%= t :commission %></td>
          <td><%= humanized_money_with_symbol @payslip.commission %></td>
        </tr>
        <tr>
          <th><%= t :total_payment %></th>
          <td><%= humanized_money_with_symbol @payslip.commission+@payslip.base_salary %></td>
        </tr>
      </tbody>

      <% if @claims %>
        <thead>
          <th colspan="2"><center><%= t :claims %></center></th>
        </thead>
        <tbody>
          <% @claims.each do |claim|%>
            <tr>
              <td><%= claim.subject %></td>
              <td><%= humanized_money_with_symbol claim.amount %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
      
      <% if @affected_leave %>
        <thead>
          <th colspan="2"><center><%= t :affected_leave %></center></th>
        </thead>
        <tbody>
          <% @affected_leave.each do |leave| %>
            <tr>
              <td><%= leave.leave_type.name %></td>
              <td> 
                <% if leave.leave_type.type == "LeaveSubstraction" %>
                  <%= humanized_money_with_symbol -(@payslip.base_salary_cents/leave.leave_type.divide_by_days*(leave.duration_seconds/working_hours/60/60)/100) %>
                <% elsif leave.leave_type.type == "LeaveAddition" %>
                  <%= humanized_money_with_symbol @payslip.base_salary_cents/leave.leave_type.divide_by_days*(leave.duration_seconds/working_hours/60/60)/100 %>
                <% else %>
                  <%= humanized_money_with_symbol 0 %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
      

      <thead>
        <th colspan="2"><center><%= t :others %></center></th>
      </thead>

      <tbody>
        
        <% @payslip.payslip_settings.each do |payslip_setting| %>
          <% if payslip_setting.positive? %>
            <tr>
              <td><%=payslip_setting.name%></td>
              <td><%=humanized_money_with_symbol @payslip.calculate(payslip_setting, @base_salary_cents)/100%></td>
            </tr>
          <% else %>
            <tr>
              <td><%=payslip_setting.name%></td>
              <td><%=humanized_money_with_symbol @payslip.calculate(payslip_setting, @base_salary_cents)/100%></td>
            </tr>
          <% end %>

          <%@total = @total + @payslip.calculate(payslip_setting, @base_salary_cents)%>   
        <% end %>
      </tbody>
    </table>
    
    <% @total = @total + @payslip.commission_cents + (@claims ? (@claims.sum :amount_cents) : 0)%>
    <table class="large-12">
      <thead>
         <tr>
            <th><%= t :net_pay %></th>
            <th><%= humanized_money_with_symbol (@total+@base_salary_cents).to_f/100 %></th>
          </tr>
         <tr>
            <th><%= t :note %></th>
            <th><%= @payslip.note %></th>
          </tr>
      </thead>
    </table>
    <%= link_to t(:back), :back, class: "button success" %>
    <%= link_to t(:print), print_salary_path(payslip_id: @payslip.id), target: "_blank", class: "button success" %>
  </div>
</div>

app/views/home/sign_up.html.erb
<div class="row sign_in">
  <div class="large-6 large-centered columns panel">
    <div class="devise-container">
      <h2><%= t :sign_up %></h2>

      <%= simple_form_for(resource, wrapper: :custom, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <%= render '/shared/error_message', object: f.object %>

        <div class="form-inputs">
          <%= f.input :email, :autofocus => true %>
          <%= f.input :password %>
          <%= f.input :password_confirmation %>

          <div class="row">
            <div class="large-3 small-3 columns"></div>
            <div class="large-9 small-9 columns">
              <div class="form-actions">
                <%= f.button :submit, t(:sign_up) %>
                or
                <%= render "devise/shared/links" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>

  </div>
</div>